"""Active Directory security tool definitions (12 tools)."""

AD_TOOLS = (
    {
        "name": "enumerate_domain",
        "description": "Enumerate Active Directory domain information including domain controllers, trusts, and forest details.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name to enumerate"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address (optional)"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "enumerate_ad_users",
        "description": "Enumerate Active Directory users with details like descriptions, group memberships, and account properties. Identify high-value targets.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "filter": {"type": "string", "description": "LDAP filter to apply (optional)"},
                "attributes": {"type": "array", "items": {"type": "string"}, "description": "Specific attributes to retrieve"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "enumerate_ad_groups",
        "description": "Enumerate Active Directory groups and their memberships. Identify privileged groups like Domain Admins, Enterprise Admins.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "privileged_only": {"type": "boolean", "description": "Only return privileged groups", "default": False},
                "include_members": {"type": "boolean", "description": "Include group member enumeration", "default": True},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "enumerate_ad_computers",
        "description": "Enumerate Active Directory computer accounts with details like OS, last logon, and service accounts.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "filter": {"type": "string", "description": "Filter for computer types (e.g., servers, workstations)"},
                "active_only": {"type": "boolean", "description": "Only return recently active computers", "default": True},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "check_ad_password_policy",
        "description": "Check Active Directory password policy settings including complexity, length, age, and lockout policies.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "check_fine_grained": {"type": "boolean", "description": "Check fine-grained password policies", "default": True},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "check_kerberoastable",
        "description": "Identify Kerberoastable accounts (service accounts with SPNs that can be targeted for credential cracking).",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "request_tickets": {"type": "boolean", "description": "Request TGS tickets for identified accounts", "default": False},
                "output_format": {"type": "string", "description": "Output format for hashes (john, hashcat)", "default": "hashcat"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "check_asrep_roastable",
        "description": "Identify AS-REP roastable accounts (accounts with pre-authentication disabled that can be targeted for credential cracking).",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication (optional for this attack)"},
                "password": {"type": "string", "description": "Password for authentication (optional for this attack)"},
                "request_hashes": {"type": "boolean", "description": "Request AS-REP hashes for identified accounts", "default": False},
                "output_format": {"type": "string", "description": "Output format for hashes (john, hashcat)", "default": "hashcat"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "check_delegation",
        "description": "Check for delegation vulnerabilities including unconstrained delegation, constrained delegation, and resource-based constrained delegation.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "delegation_types": {"type": "array", "items": {"type": "string"}, "description": "Types to check (unconstrained, constrained, rbcd)"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "enumerate_gpos",
        "description": "Enumerate Group Policy Objects and identify misconfigurations or security issues in GPO settings.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "check_permissions": {"type": "boolean", "description": "Check GPO permissions for vulnerabilities", "default": True},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "check_trusts",
        "description": "Enumerate and analyze domain trust relationships including forest trusts, external trusts, and trust authentication.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "recursive": {"type": "boolean", "description": "Recursively enumerate trusts", "default": False},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "enumerate_shares",
        "description": "Enumerate network shares on domain computers and check for misconfigurations or sensitive data exposure.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "target_hosts": {"type": "array", "items": {"type": "string"}, "description": "Specific hosts to enumerate (optional)"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "check_permissions": {"type": "boolean", "description": "Check share permissions", "default": True},
                "find_sensitive": {"type": "boolean", "description": "Search for sensitive files", "default": False},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
    {
        "name": "ad_security_assessment",
        "description": "Perform a comprehensive Active Directory security assessment covering common attack vectors and misconfigurations.",
        "input_schema": {
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Domain name"},
                "dc_ip": {"type": "string", "description": "Domain controller IP address"},
                "username": {"type": "string", "description": "Username for authentication"},
                "password": {"type": "string", "description": "Password for authentication"},
                "checks": {"type": "array", "items": {"type": "string"}, "description": "Specific checks to perform (all by default)"},
                "depth": {"type": "string", "description": "Assessment depth (quick, standard, deep)", "default": "standard"},
                "project_id": {"type": "string", "description": "Project ID"},
                "target_id": {"type": "string", "description": "Target ID"},
            },
            "required": ["domain", "project_id", "target_id"],
        },
    },
)
